### PR TITLE
Removed deprecated `auto` option from `_config.yml`

### PR DESCRIPTION
**Pull request by alexdantas**
On new versions of Jekyll, the `auto` option got deprecated.
Instead users should use the `--watch option` like on `jekyll serve --watch`

### CODE REVIEW

**Comment by alexdantas** [comment]
If you do accept this change, I could make it clear on the `README` :smiley:

**Comment by hendricius** [comment]
Thanks! Cheers to Brazil.

**Comment by alexdantas** [comment]
Thank _you_! This project made me finally switch from `awestruct` to `jekyll`

**Comment by hendricius** [comment]
We need to adjust this, latest versions of jekyll already have sass already
included.

**Pull request merged**
